In [1]:
import pandas as pd
import numpy as np
# Generate 20 random integers uniformly between 0 and 99
small_counts = np.random.randint(0, 100, 20)
print(small_counts)
# Map to evenly spaced bins 0-9 by division
print(np.floor_divide(small_counts, 10))

large_counts = [296, 8286, 64011, 80, 3, 725, 867, 2215, 7689, 11495, 91897, 44, 28, 7971,
926, 12]
print(np.floor(np.log10(large_counts)))
#Map the counts to quartiles into 4 bins (quartile)
print(pd.qcut(large_counts, 4, labels=False))
#convert large_counts into series data
large_counts_series = pd.Series(large_counts)
print(large_counts_series)
print(large_counts_series.quantile([0.25, 0.5, 0.75]))

[93 60 82  5 84 80 20 43 49 93 40 31 21 65 46 21 13 14 43 21]
[9 6 8 0 8 8 2 4 4 9 4 3 2 6 4 2 1 1 4 2]
[2. 3. 4. 1. 0. 2. 2. 3. 3. 4. 4. 1. 1. 3. 2. 1.]
[1 3 3 1 0 1 1 2 2 3 3 0 0 2 2 0]
0       296
1      8286
2     64011
3        80
4         3
5       725
6       867
7      2215
8      7689
9     11495
10    91897
11       44
12       28
13     7971
14      926
15       12
dtype: int64
